version: '3.8'

services:
  # ───────────────────────────────────────────────
  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sala
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ───────────────────────────────────────────────
  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: my_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # using the "server" command with a data directory
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
