version: '3.8'

services:
  # ───────────────────────────────────────────────
  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sala
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ───────────────────────────────────────────────
  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: my_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - ./volumes/minio:/data

  # ───────────────────────────────────────────────
  # Redis in-memory data store
  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
